import re
from functools import partial
from math import exp

import datasets
from packaging import version


from lm_eval.api.instance import Instance
from lm_eval.api.task import ConfigurableTask

from typing import Optional

subjects = {
    'electrical_engineering', 'marketing', 'computer_security', 'moral_disputes', 
    'high_school_mathematics', 'virology', 'college_computer_science', 'moral_scenarios', 
    'jurisprudence', 'high_school_chemistry', 'us_foreign_policy', 'medical_genetics', 
    'college_mathematics', 'college_medicine', 'high_school_us_history', 'machine_learning', 
    'professional_accounting', 'high_school_government_and_politics', 'high_school_microeconomics', 
    'conceptual_physics', 'high_school_macroeconomics', 'high_school_world_history', 
    'philosophy', 'sociology', 'high_school_geography', 'econometrics', 'nutrition', 
    'world_religions', 'high_school_computer_science', 'business_ethics', 'global_facts', 
    'anatomy', 'high_school_european_history', 'professional_law', 'management', 
    'high_school_biology', 'public_relations', 'astronomy', 'professional_medicine', 
    'high_school_psychology', 'college_chemistry', 'human_sexuality', 'logical_fallacies', 
    'miscellaneous', 'high_school_statistics', 'professional_psychology', 'human_aging', 
    'elementary_mathematics', 'formal_logic', 'college_physics', 'high_school_physics', 
    'abstract_algebra', 'prehistory', 'clinical_knowledge', 'international_law', 
    'college_biology', 'security_studies'
}

def _exact_match(references: dict[str, str], predictions: dict[str, str]):
    mean_acc = 0
    for pred, ref in zip(predictions, references):
        correct_letter = ["A", "B", "C", "D"][ref["correct_answer"]]
        prediction = pred["prediction_text"]
        if any(correct_letter in str(p).strip() for p in prediction):
            mean_acc += 1
    return mean_acc / len(predictions)


def _exact_match_agg(key, items):
    predictions, references = zip(*items)

    return _exact_match(predictions=predictions, references=references)


class MMLUBaseTask(ConfigurableTask):
    VERSION = "0.0.1"
    DATASET_PATH = "INSAIT-Institute/mmlu_ukr"
    DATASET_NAME = None

    def __init__(self, config=None):
        super().__init__(config={"metadata": {"version": self.VERSION}})

    def download(
        self,
        data_dir: Optional[str] = None,
        cache_dir: Optional[str] = None,
        download_mode=None,
    ) -> None:

        self.dataset = datasets.load_dataset(
            path=self.DATASET_PATH,
            name=self.DATASET_NAME,
            data_dir=data_dir,
            cache_dir=cache_dir,
            download_mode=download_mode,
        )

    def has_training_docs(self):
        return False

    def has_validation_docs(self):
        return False

    def has_test_docs(self):
        return True
    
    def test_docs(self):
        return self.dataset["test"]
    
    def training_docs(self):
        return self.dataset["dev"]
    
    def validation_docs(self):
        return self.dataset["validation"]
    

    def doc_to_text(self, doc):
        options = ["A", "B", "C", "D", "E"]
        options_text = "\n".join([f"{option}. {answer}" for option, answer in zip(options, doc["choices"])])
        return (
            "Питання: "
            + doc["question"].strip()
            + "\n"
            + options_text
            + "\n"
            + "Відповідь:"
        )

    def should_decontaminate(self):
        return True

    def doc_to_decontamination_query(self, doc):
        return doc["question"]

    def doc_to_target(self, doc):
        return ["A", "B", "C", "D"][doc["answer"]]

    def construct_requests(
        self, doc, ctx, chat_template=None, apply_chat_template=False, **kwargs
    ):
        """Uses RequestFactory to construct Requests and returns an iterable of
        Requests which will be sent to the LM.

        :param doc:
            The document as returned from training_docs, validation_docs, or test_docs.
        :param ctx: str
            The context string, generated by fewshot_context. This includes the natural
            language description, as well as the few shot examples, and the question
            part of the document for `doc`.
        """

        return [
            Instance(
                request_type="generate_until",
                doc=doc,
                arguments=(ctx, {"until": ["\n"]}),
                idx=0,
                **kwargs,
            ),
        ]

    def process_results(self, doc, results):
        """Take a single document and the LM results and evaluates, returning a
        dict where keys are the names of submetrics and values are the values of
        the metric for that one document

        :param doc:
            The document as returned from training_docs, validation_docs, or test_docs.
        :param results:
            The results of the requests created in construct_requests.
        """
        continuation = results

        predictions = {
            "question": doc["question"],
            "answers": doc["choices"],
            "prediction_text": continuation,
        }

        references = {
            "question": doc["question"],
            "correct_answer": doc["answer"],
        }

        return {
            "exact": (
                predictions,
                references,
            )
        }

    def aggregation(self):
        """
        :returns: {str: [float] -> float}
            A dictionary where keys are the names of submetrics and values are
            functions that aggregate a list of metrics
        """
        return {
            "exact": partial(
                _exact_match_agg, "exact"
            ),

        }

    def higher_is_better(self):
        """
        :returns: {str: bool}
            A dictionary where keys are the names of submetrics and values are
            whether a higher value of the submetric is better
        """
        return {
            "exact": True,
        }


class MMLUElectricalEngineeringTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "electrical_engineering")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "electrical_engineering")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "electrical_engineering")


class MMLUMarketingTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "marketing")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "marketing")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "marketing")


class MMLUComputerSecurityTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "computer_security")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "computer_security")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "computer_security")


class MMLUMoralDisputesTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "moral_disputes")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "moral_disputes")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "moral_disputes")


class MMLUHighSchoolMathematicsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_mathematics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_mathematics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_mathematics")


class MMLUVirologyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "virology")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "virology")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "virology")


class MMLUCollegeComputerScienceTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "college_computer_science")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "college_computer_science")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "college_computer_science")


class MMLUMoralScenariosTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "moral_scenarios")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "moral_scenarios")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "moral_scenarios")


class MMLUJurisprudenceTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "jurisprudence")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "jurisprudence")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "jurisprudence")


class MMLUHighSchoolChemistryTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_chemistry")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_chemistry")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_chemistry")


class MMLUUsForeignPolicyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "us_foreign_policy")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "us_foreign_policy")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "us_foreign_policy")


class MMLUMedicalGeneticsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "medical_genetics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "medical_genetics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "medical_genetics")


class MMLUCollegeMathematicsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "college_mathematics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "college_mathematics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "college_mathematics")


class MMLUCollegeMedicineTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "college_medicine")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "college_medicine")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "college_medicine")


class MMLUHighSchoolUsHistoryTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_us_history")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_us_history")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_us_history")


class MMLUMachineLearningTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "machine_learning")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "machine_learning")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "machine_learning")


class MMLUProfessionalAccountingTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "professional_accounting")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "professional_accounting")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "professional_accounting")


class MMLUHighSchoolGovernmentAndPoliticsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_government_and_politics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_government_and_politics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_government_and_politics")


class MMLUHighSchoolMicroeconomicsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_microeconomics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_microeconomics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_microeconomics")


class MMLUConceptualPhysicsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "conceptual_physics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "conceptual_physics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "conceptual_physics")


class MMLUHighSchoolMacroeconomicsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_macroeconomics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_macroeconomics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_macroeconomics")


class MMLUHighSchoolWorldHistoryTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_world_history")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_world_history")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_world_history")


class MMLUPhilosophyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "philosophy")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "philosophy")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "philosophy")


class MMLUSociologyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "sociology")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "sociology")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "sociology")


class MMLUHighSchoolGeographyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_geography")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_geography")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_geography")


class MMLUEconometricsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "econometrics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "econometrics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "econometrics")


class MMLUNutritionTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "nutrition")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "nutrition")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "nutrition")


class MMLUWorldReligionsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "world_religions")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "world_religions")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "world_religions")


class MMLUHighSchoolComputerScienceTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_computer_science")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_computer_science")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_computer_science")


class MMLUBusinessEthicsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "business_ethics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "business_ethics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "business_ethics")


class MMLUGlobalFactsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "global_facts")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "global_facts")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "global_facts")


class MMLUAnatomyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "anatomy")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "anatomy")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "anatomy")


class MMLUHighSchoolEuropeanHistoryTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_european_history")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_european_history")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_european_history")


class MMLUProfessionalLawTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "professional_law")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "professional_law")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "professional_law")


class MMLUManagementTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "management")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "management")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "management")


class MMLUHighSchoolBiologyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_biology")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_biology")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_biology")


class MMLUPublicRelationsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "public_relations")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "public_relations")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "public_relations")


class MMLUAstronomyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "astronomy")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "astronomy")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "astronomy")


class MMLUProfessionalMedicineTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "professional_medicine")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "professional_medicine")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "professional_medicine")


class MMLUHighSchoolPsychologyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_psychology")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_psychology")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_psychology")


class MMLUCollegeChemistryTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "college_chemistry")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "college_chemistry")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "college_chemistry")


class MMLUHumanSexualityTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "human_sexuality")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "human_sexuality")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "human_sexuality")


class MMLULogicalFallaciesTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "logical_fallacies")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "logical_fallacies")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "logical_fallacies")


class MMLUMiscellaneousTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "miscellaneous")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "miscellaneous")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "miscellaneous")


class MMLUHighSchoolStatisticsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_statistics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_statistics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_statistics")


class MMLUProfessionalPsychologyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "professional_psychology")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "professional_psychology")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "professional_psychology")


class MMLUHumanAgingTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "human_aging")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "human_aging")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "human_aging")


class MMLUElementaryMathematicsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "elementary_mathematics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "elementary_mathematics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "elementary_mathematics")


class MMLUFormalLogicTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "formal_logic")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "formal_logic")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "formal_logic")


class MMLUCollegePhysicsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "college_physics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "college_physics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "college_physics")


class MMLUHighSchoolPhysicsTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "high_school_physics")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "high_school_physics")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "high_school_physics")


class MMLUAbstractAlgebraTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "abstract_algebra")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "abstract_algebra")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "abstract_algebra")


class MMLUPrehistoryTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "prehistory")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "prehistory")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "prehistory")


class MMLUClinicalKnowledgeTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "clinical_knowledge")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "clinical_knowledge")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "clinical_knowledge")


class MMLUInternationalLawTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "international_law")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "international_law")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "international_law")


class MMLUCollegeBiologyTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "college_biology")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "college_biology")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "college_biology")


class MMLUSecurityStudiesTask(MMLUBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["subject"] == "security_studies")
        self.dataset["dev"] = self.dataset["dev"].filter(lambda sample: sample["subject"] == "security_studies")
        self.dataset["validation"] = self.dataset["validation"].filter(lambda sample: sample["subject"] == "security_studies")

