import re
from functools import partial
from math import exp

import datasets
from packaging import version


from lm_eval.api.instance import Instance
from lm_eval.api.task import ConfigurableTask

from typing import Optional


def _exact_match(references: dict[str, str], predictions: dict[str, str]):
    mean_acc = 0
    for pred, ref in zip(predictions, references):
        correct_letter = ["A", "B", "C", "D", "E"][ref["correct_answer"]]
        prediction = pred["prediction_text"]
        if any(correct_letter in str(p).strip() for p in prediction):
            mean_acc += 1
    return mean_acc / len(predictions)


def _exact_match_agg(key, items):
    predictions, references = zip(*items)

    return _exact_match(predictions=predictions, references=references)


class ZnoBaseTask(ConfigurableTask):
    VERSION = "0.0.1"
    DATASET_PATH = "INSAIT-Institute/zno_ukr"
    DATASET_NAME = None

    def __init__(self, config=None):
        super().__init__(config={"metadata": {"version": self.VERSION}})

    def download(
        self,
        data_dir: Optional[str] = None,
        cache_dir: Optional[str] = None,
        download_mode=None,
    ) -> None:

        self.dataset = datasets.load_dataset(
            path=self.DATASET_PATH,
            name=self.DATASET_NAME,
            data_dir=data_dir,
            cache_dir=cache_dir,
            download_mode=download_mode,
        )

    def has_training_docs(self):
        return False

    def has_validation_docs(self):
        return False

    def has_test_docs(self):
        return True
    
    def test_docs(self):
        return self.dataset["test"]
    

    def doc_to_text(self, doc):
        options = ["A", "B", "C", "D", "E"]
        options_text = "\n".join([f"{option}. {answer}" for option, answer in zip(options, doc["answers"])])
        return (
            "Питання: "
            + doc["question"].strip()
            + "\n"
            + options_text
            + "\n"
            + "Відповідь:"
        )

    def should_decontaminate(self):
        return True

    def doc_to_decontamination_query(self, doc):
        return doc["question"]

    def doc_to_target(self, doc):
        return ["A", "B", "C", "D", "E"][doc["correct_answer"] - 1]

    def construct_requests(
        self, doc, ctx, chat_template=None, apply_chat_template=False, **kwargs
    ):
        """Uses RequestFactory to construct Requests and returns an iterable of
        Requests which will be sent to the LM.

        :param doc:
            The document as returned from training_docs, validation_docs, or test_docs.
        :param ctx: str
            The context string, generated by fewshot_context. This includes the natural
            language description, as well as the few shot examples, and the question
            part of the document for `doc`.
        """

        return [
            Instance(
                request_type="generate_until",
                doc=doc,
                arguments=(ctx, {"until": ["\n"]}),
                idx=0,
                **kwargs,
            ),
        ]

    def process_results(self, doc, results):
        """Take a single document and the LM results and evaluates, returning a
        dict where keys are the names of submetrics and values are the values of
        the metric for that one document

        :param doc:
            The document as returned from training_docs, validation_docs, or test_docs.
        :param results:
            The results of the requests created in construct_requests.
        """

        continuation = results


        predictions = {
            "question": doc["question"],
            "answers": doc["answers"],
            "prediction_text": continuation,
        }

        references = {
            "question": doc["question"],
            "correct_answer": doc["correct_answer"] - 1,
        }

        return {
            "exact": (
                predictions,
                references,
            )
        }

    def aggregation(self):
        """
        :returns: {str: [float] -> float}
            A dictionary where keys are the names of submetrics and values are
            functions that aggregate a list of metrics
        """
        return {
            "exact": partial(
                _exact_match_agg, "exact"
            ),

        }

    def higher_is_better(self):
        """
        :returns: {str: bool}
            A dictionary where keys are the names of submetrics and values are
            whether a higher value of the submetric is better
        """
        return {
            "exact": True,
        }


class ZnoGeographyTask(ZnoBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["source"] == "geography")

class ZnoHistoryTask(ZnoBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["source"] == "history")

class ZnoMathTask(ZnoBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["source"] == "math")

class ZnoLanguageAndLiteratureTask(ZnoBaseTask):
    def __init__(self, config=None):
        super().__init__(config=config)

    def download(self, data_dir=None, cache_dir=None, download_mode=None):
        super().download(data_dir, cache_dir, download_mode)
        self.dataset["test"] = self.dataset["test"].filter(lambda sample: sample["source"] == "ukrainian-language-and-literature")
