include: ../../ukrainian_bench/long_flores_uk/long_flores_en-uk.yaml
task: long_flores_en-uk
task_alias: long_flores_en-uk
doc_to_text: "Translate this text into Ukrainian:\n{{sentence_eng_Latn}}\n\nResponse format must be <translation>переклад українською</translation>."
generation_kwargs:
  max_gen_toks: 65536
  until:
    - "==sdfAcxbvgg/=/=/="
filter_list:
  - name: extract_translation
    filter:
      - function: regex
        regex_pattern: '(?s)<translation>\s*(.*?)\s*</translation>'
        group_select: 0
        fallback: ""
      - function: take_first
